### ISSUE TITLE
Make a v2023 release

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline1#6]
This would be the first Github release. We should create a tag and upload some binaries. For now the latest binaries are on SourceForge.

@rdeltour Is this something you would be willing to do?

**Comment by rdeltour** [comment]
> @rdeltour Is this something you would be willing to do?

Sure, will do!

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline1/releases/tag/untagged-8c09ec00baf979faa138.

**Comment by bertfrees** [comment]
Oh wait, binaries haven't been uploaded yet. @rdeltour can you do it?

**Comment by rdeltour** [comment]
> Oh wait, binaries haven't been uploaded yet. @rdeltour can you do it?

The binaries were already in the draft release, which I just published:
https://github.com/daisy/pipeline1/releases/download/v20230619/pipeline-20230619.zip
